name: My Daily Commit

on:
  schedule:
    - cron: '0 6 * * *'  # Run every day at 6 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create file and commit
        run: |
          FILE="commit_number.md"
          if [ ! -f "$FILE" ]; then
            echo "Hello, my name is MaiTrang" > "$FILE"
            echo "commit number: 1" >> "$FILE"
          else
            CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
            if [ -z "$CURRENT_COUNT" ]; then
              CURRENT_COUNT=0
            fi
            NEXT_COUNT=$((CURRENT_COUNT + 1))
            sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
          fi
          git config --global user.name "maitnt"
          git config --global user.email "maitrangnt2210@gmail.com"
          git add "$FILE"
          git commit -m "Hello, my name is MaiTrang nice to meet you"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/maitnt/maitnt.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
